# Due to the limitation that for CLOUDFRONT WAFv2 resources must be created in the US East (N.Virginia) Region

Description: "CMS Cloud - DLTA WAFv2 - create WebACL resource in us-east-1. This will be used by DLTA deployment in us-west-2, "

Parameters:
  WhiteListIPs:
    Type: CommaDelimitedList
    Description: List of IP ranges that are allowed to access the solution. 
    Default: "52.5.212.71/32, 52.20.26.200/32, 34.196.35.156/32, 34.225.217.125/32, 3.215.42.28/32, 54.86.8.83/32"

Conditions:
  WhiteListIPProvided: !Not 
    - !Equals 
      - !Select [ "0", !Ref WhiteListIPs ]
      - ''
Resources:
  
### Added WebACL to block all traffic by default, but allow traffic from CMS Cloud VPN
  WebACL:
    Condition: WhiteListIPProvided
    Type: 'AWS::WAFv2::WebACL'
    Properties: 
      Name: webacl
      Description: Web access control list for DLTA	  
      Scope: CLOUDFRONT      
      DefaultAction:       # By default all access is blocked
        Block:
          CustomResponse:
            ResponseCode: 503
      Rules: 
        - Name: WhiteListRule
          Priority: 0        
          Action: 
            Allow:
              CustomRequestHandling:
                InsertHeaders:
                  - Name: AllowActionHeader1Name
                    Value: AllowActionHeader1Value
                  - Name: AllowActionHeader2Name
                    Value: AllowActionHeader2Value
          Statement:
            IPSetReferenceStatement: 
              Arn: !GetAtt WhiteListIPSet.Arn
          VisibilityConfig: 
            CloudWatchMetricsEnabled: true
            MetricName: dlta-webacl-rule-0
            SampledRequestsEnabled: true              
      Tags: 
        - Key: component
          Value: DLTA      
      VisibilityConfig: 
        CloudWatchMetricsEnabled: true
        MetricName: dlta-webacl
        SampledRequestsEnabled: true

  WhiteListIPSet:
    Condition: WhiteListIPProvided
    Type: 'AWS::WAFv2::IPSet'
    Properties:
      Description: Web ACL White List IP Set
      Name: whitelistipset
      Scope: CLOUDFRONT
      IPAddressVersion: IPV4
      Addresses: !Ref WhiteListIPs         
Outputs:
  WebACLArn:
    Description: WebACL Arn for DLTA implementation in us-west-2 
    Value: !GetAtt WebACL.Arn
    Export:
      Name: DltaWebACLArn